### ISSUE TITLE
Name conflict

### ISSUE THREAD

**Issue by David263** [damcclean/Systatic#18]
The name "Thunderbird" is already used for a popular email client formerly part of the Mozilla/Firefox project.

**Comment by damcclean** [comment]
Hey,

Yeah, I'm aware of this. For now we'll keep the name Thunderbird but at some point in the future we'll think about a new name.

**Comment by damcclean** [comment]
Hey,

I'm going to reopen this repository. I think it would be a good time to think about renaming the project. Any ideas?
